drop table if exists computer;
drop table if exists company;

create table company (
  ca_id                        bigint not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  ca_name                      varchar(255) not null,
  constraint pk_company primary key (ca_id))
;

create table computer (
  cu_id                        bigint not null GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
  cu_name                      varchar(255) not null,
  cu_introduced                datetime NULL,
  cu_discontinued              datetime NULL,
  ca_id                        bigint default NULL,
  constraint pk_computer primary key (cu_id))
;

alter table computer add constraint fk_computer_company_1 foreign key (ca_id) references company (ca_id);
create index ix_computer_company_1 on computer (ca_id);
